sudo: required
services:
  - docker

before_install:
  - docker build -t a6s7d8/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true a6s7d8/docker-react npm run test

deploy:
  povider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket-name: "elasticbeanstalk-us-west-2"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


## for aws iam
# attach existing policies directly
beanstak - provides full access

# put aws keys in travis ci under settings
# environment variables
# AWS_ACCESS_KEY
# AWS_SECRET_KEY